# Generated by Django 4.0.4 on 2022-10-10 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(blank=True, max_length=80, null=True)),
                ('module_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(blank=True, max_length=100, null=True)),
                ('session_description', models.TextField(blank=True, null=True)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('session_time', models.TimeField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentmodules')),
                ('session_venue', models.ForeignKey(default='No Instructor Yet', on_delete=django.db.models.deletion.CASCADE, to='students.venues')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('student_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('student_cellphone', models.CharField(blank=True, max_length=100, null=True)),
                ('Faculty', models.CharField(blank=True, choices=[('Education', 'Education'), ('Enginnering', 'Enginnering'), ('Law', 'Law'), ('Humanities', 'Humanities'), ('Arts', 'Arts'), ('Sciences', 'Sciences'), ('Health Science', 'Health Sciences')], max_length=100, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('modules', models.ManyToManyField(blank=True, related_name='modules', to='students.studentmodules')),
                ('name', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentinfo')),
            ],
        ),
    ]
