# Generated by Django 4.0.4 on 2022-10-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentsession_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsession',
            name='student_image',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='student_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
