# Generated by Django 4.0.4 on 2022-10-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_studentinfo_modules_studentinfo_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='Faculty',
            field=models.CharField(blank=True, choices=[('Education', 'Education'), ('Enginnering', 'Enginnering'), ('Law', 'Law'), ('Humanities', 'Humanities'), ('Arts', 'Arts'), ('Sciences', 'Sciences'), ('Health Science', 'Health Sciences')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='student_cellphone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
