# Generated by Django 4.0.4 on 2022-10-04 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_studentmodules_module_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodules',
            name='module_instructor',
        ),
    ]
