# Generated by Django 4.0.4 on 2022-10-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='session_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='session_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='session_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
