# Generated by Django 4.0.4 on 2022-10-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_attendance_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsession',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
