# Generated by Django 4.0.4 on 2022-10-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherinfo',
            old_name='email',
            new_name='teacher_email',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='age',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='dept_type',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='sub_type',
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='Faculty',
            field=models.CharField(blank=True, choices=[('Education', 'Education'), ('Enginnering', 'Enginnering'), ('Law', 'Law'), ('Humanities', 'Humanities'), ('Arts', 'Arts'), ('Sciences', 'Sciences'), ('Health Science', 'Health Sciences')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
