# Generated by Django 4.0.4 on 2022-10-04 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_studentmodules_module_instructor'),
        ('teachers', '0003_teacherinfo_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_modules', to='students.studentmodules'),
        ),
    ]
