# Generated by Django 4.0.4 on 2022-10-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_teacherinfo_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfo',
            name='teacher_cellphone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
